djangoProject8/djangoProject8/AdManagement/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show-ads/', views.ShowAds.as_view(), name='show-ads'),
    path('create-ad/', views.AdFormView.as_view(), name='create-ad'),
    path('click/<int:pk>/', views.CountClickAndRedirect.as_view(), name='count-click'),
    path('ad-detail/<int:pk>/', views.AdDetail.as_view(), name='ad-detail')
]

djangoProject8/djangoProject8/djangoProject8/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AdManagement.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject8/djangoProject8/AdManagement/models.py
from collections import OrderedDict

from django.db import models

# Create your models here.


class Advertiser(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Ad(models.Model):
    Title = models.CharField(max_length=200)
    Img = models.ImageField(upload_to='img/', default='de.jpg')
    Link = models.URLField()
    Adv = models.ForeignKey(Advertiser, on_delete=models.CASCADE)
    # approve = models.BooleanField(default=True)

    def __str__(self):
        return self.Title

    def number_of_clicks(self):
        dict = {}
        for hour in range(0, 24):
            dict[str(hour) + "-" + str(hour+1)] = self.click_set.filter(ad__click__C_date__hour__range=(hour, hour+1)).count()
        return dict

    def number_of_views(self):
        dict = {}
        for hour in range(0, 24):
            dict[str(hour) + "-" + str(hour+1)] = self.view_set.filter(ad__view__V_date__hour__range=(hour, hour+1)).count()
        return dict

    def getAveViewAndClickTimeDif(self):

        sum = 0
        for click in self.click_set.all():
            time = click.C_date - \
                   self.view_set.filter(ip=click.ip).filter(V_date__lt=click.C_date)[0].V_date
            sum += time.seconds

        if self.click_set.exists():
            return sum / self.click_set.count()
        else:
            return "we have no clicks on this ad"


class Click(models.Model):
    C_date = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField(default='000.000.0.0')
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)

    def __str__(self):
        return self.ad.Title+" clicked by "+self.ip


class View(models.Model):
    V_date = models.DateTimeField(auto_now_add=True)
    ip = models.GenericIPAddressField(default='000.000.0.0')
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)

    def __str__(self):
        return self.ad.Title+" viewed by "+self.ip

djangoProject8/djangoProject8/AdManagement/forms.py
from django import forms


class Form(forms.Form):
    advertiser_id = forms.IntegerField()
    Img = forms.ImageField()
    Title = forms.CharField()
    Link = forms.URLField()

djangoProject8/djangoProject8/AdManagement/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import RedirectView, FormView, base, DetailView
from .models import Ad, Advertiser, View, Click
from .forms import Form
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime


# def showAds(request):
#     advertisers = Advertiser.objects.all()
#     context = {"advertisers": advertisers}
#
#     # increase ads views
#     ads = Ad.objects.all()
#     for ad in ads:
#         view = View.objects.create(
#             view_date=datetime.now(),
#             user_ip=request.META['REMOTE_ADDR'],
#             ad=ad
#         )
#         view.save()
#
#     return render(request, 'advertiser_management/ads.html', context)

class ShowAds(base.TemplateView):
    template_name = 'ads.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['advertisers'] = Advertiser.objects.all()

        # increase ads views
        ads = Ad.objects.all()
        for ad in ads:
            view = View.objects.create(
                ip=self.request.META['REMOTE_ADDR'],
                ad=ad
            )
            view.save()

        return context


class CountClickAndRedirect(RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'count-click'

    def get_redirect_url(self, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=kwargs['pk'])
        click = Click.objects.create(
            ip=self.request.META['REMOTE_ADDR'],
            ad=ad
        )
        click.save()
        self.url = ad.Link
        return ad.Link


class AdFormView(FormView):
    form_class = Form
    template_name = 'form.html'

    def form_valid(self, form):
        advertiser_id = form.cleaned_data.get("advertiser_id")
        image = form.cleaned_data.get("Img")
        title = form.cleaned_data.get("Title")
        link = form.cleaned_data.get("Link")
        ad = Ad.objects.create(
            Title=title,
            Img=image,
            Link=link,
            Adv=get_object_or_404(Advertiser, pk=advertiser_id)
        )
        ad.save()
        return HttpResponseRedirect(reverse('show-ads'))


class AdDetail(DetailView):
    model = Ad
    template_name = 'ad-detail.html'

djangoProject8/djangoProject8/templates/ad-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Ad id {{ object.id }}</h1>
<p>number of clicks = {{ object.number_of_clicks }}</p>
<p>click rate to view = {{ object.number_of_views }}</p>

</body>
</html>

djangoProject8/djangoProject8/templates/ads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <title>Ad</title>
</head>
<body>
<div class="container" dir="rtl">
    {% for advertiser in advertisers %}
        <div class="card mt-2 p-2">
            <h5 class="card-title">{{ advertiser.name }}</h5>
            <div class="card-body">
                <div class="row">
		    {% for ad in advertiser.ad_set.all %}
		        <div class="card col-md-2 p-0 mx-2">
		            <a href="/click/{{ ad.id }}/">
		                <img src=" {{ ad.Img.url}}" alt="{{ ad.Title }}"
		                     class="card-img-top">
		                <div class="card-body">
		                    <span>{{ ad.title }}</span>
		                </div>
		            </a>
		        </div>
		    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>
</body>
</html>

djangoProject8/djangoProject8/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> save </button>
    </form>
</body>
</html>>